- src/table.coffee
A table name of the form *schema*.*table* is parsed as *@database* = *schema* and *@path* = *schema*.*schema*.*table*.  This is wrong, as *@database* should be null and *@path* should be *schema*.*table*.
* Note: I do not know CoffeeScript. I tested the changes by editing the table.js file, and it worked.
> Fix name parsing in Table constructor

- src/tedious.coffee
Call to connection.newBulkLoad was using the table name, not the table path, which includes the database and schema.  This meant that database and schema were being ignored.
* Note: I do not know CoffeeScript.  I tested the changes by editing the tedious.js file, and it worked.
> Fix Tedious table name in newBulkLoad

- src/msnodesql.coffee
In case of an error when executing sql query, the connection isnt returned back to the pool.
This changes fixes the issue.
> Release connection to pool on query error

- package.json
Have verified that as of 1.12.2, NTLM auth is working again.
> Update tedious version to 1.12.2

- src/main.coffee
When using the bulk method without a callback, the returned promise
should resolve with the row count to match the normal callback
behavior.
> Update bulk: resolve promise with rowCount

- src/tedious.coffee
If a query fails because of a connection error, the tedious connection will emit an "error" event.
But in node-mssql, the Tedious Request class does not listen for this event - only for the "errorMessage" event, which is emitted on e.g. syntax errors.
So Tedious Request's error handler should listen to both events. With one difference: Tedious' own errorMessage handler actively creates a request error and returns it to node-mssql's Tedious Request.
But everwhere the "error" event is emitted from tedious (e.g. in SocketError), no request error is created.
As a result, the Tedious Request never calls its callback on connection errors.
This change makes sure that the callback is called with a proper error object, as would be expected.
There is also logic to ensure that the callback is only …
> Make sure that tedious Request calls callback function on errors.

- src/tedious.coffee
At the moment native XML is not supporting cyrillic and chinese symbols.
This is caused by convertion of xml to varchar in file terious.coffee. 
In order to fix this, varchar should be changed to nvarchar.
> fix: support for utf8 characters in xml

- lib/tedious.js
When checking for the connection.config.parseJSON flag the coffeescript incorrectly adds "this." to the front even though the connection is the ambient scope variable "connection" -- should also be corrected in tedious.coffee to remove the '@'
Found this when returning JSON column
> Fixed invalid connection ref in handler

- README.md
This link was throwing 404 error earlier.
> Updated URL for TediousJS api doc

- lib/connectionstring.js
- test/common/unit.js
I need to have the MultiSubnetFailover property for my DB, and it doesn't get picked up when you use the connection string parser in this library, even though tedious supports the property in the config object.
> Adding support for the MultiSubnetFailover option in connection strings

- lib/msnodesqlv8.js
Add event handler to subscribe to msnodesqlv8 info event and dispatch through node-mssql request.  Also when providing an object of arguments to build the connection string, the resulting connection string ends in this format:  
```
Driver={SQL Server Native Client 11.0};Server={localhost,1433};Database={MyDatabase};Uid={};Pwd={};Trusted_Connection={Yes};
```
The remaining brackets cause the connection string to be invalid. Also replaced ,1433 from the connection string if using the default port.
Usage example:
```
req.on('info', infoMessage => {
console.log(infoMessage.message); // Could be PRINT message, Rows affected, statistics, time etc
});
```
> Add support for informational message capturing with msnodesqlv8

- README.md
Currently it is stated that the UDP port **1444** should be reachable in order to request info from SQL Server Browser, however, the port used by Tedious is **1434**.
From: tedious/lib/instance-lookup.js
```javascript
15.  var SQL_SERVER_BROWSER_PORT = 1434;
16.  var TIMEOUT = 2 * 1000;
17.  var RETRIES = 3;
````
> Fixed instructions regarding SQL Server Browser (port 1434)

- lib/base.js
IF i use ES6 style promises
const sql = require('mssql')
sql.connect(config).then(() => {
query1 = sql.query`select * from mytable where id = ${value}`
query2 = sql.query`select * from mytable where id = ${value}`
return Promise.all([ query1, query2 ]).then(dataset => {
return dataset;
});
}).then(result => {
console.dir(result)
}).catch(err => {
// ... error checks
})
and if one of requests fails (by timeout for example), application gets critical error "can't find property release of null (pool.release)"
> fix error unexisting connection-object pool

- lib/msnodesqlv8.js
I noticed that while using a connection pool and the msnodesqlv8 driver that my `options: { encrypt: true }` setting was getting ignored and the connection was still happening in plain text without any notification or warning. I observed this while inspecting the packets with Wireshark.
I believe the following code resolves the issue. I'm not super familiar with the code base so this may not be the best solution and edits (or new pull requests) by anyone are welcomed.
> Fixed issue where the encrypt option was getting ignored

- lib/base.js
- package.json
We are using MS SQL connection pools and found that template literals did not work; I extracted the code for cleaning and processing the template literals from `_template` into `_processTemplate`.
This is so it can be used to generate T-SQL commands for `Request.query` where a template literal would give an object as the first argument.
> Connection Pool Template Strings/Tagged functions

- lib/tedious.js
Fixes #610
Closes #671
The number of available connections will routinely, gradually reduce to 0 over a period of hours. This seems to be prevalent on Azure hosted SQL Server instances.
We've spent a few weeks monitoring the problem and logging out connection pool metrics - the number of available connections (that can be loaned), the number of pool factory create operations (resolves to `_poolCreate` in this library), and so on...
```json
{"pool_all_objects_size":"9","potentially_allocable_resource_count":"10","threshold":"10","pool_reported_size":"10","available_connections":"9","factory_create_operations":"1"}
```
Unless you're monitoring connection metrics yourself, the problem will manifest when you see EREQUEST errors. We believe this to be due to the generic pool library being …
> Fix connections in the pool depleting due to unfulfilled Promises and timeouts

- package-lock.json
- package.json
This just bumps us to a BC update containing bugfixes: https://github.com/tediousjs/tedious/pull/769.
In theory this library could be upgraded to also drop Node v4 and support Tedious 3.0.
Closes #711
Fixes #470
> Update Tedious dependency to 2.7.1

- lib/base.js
Fixes #696 
this._poolDestroy returns a promise that gets orphaned. Instead of just continuing, wait for the Promise from the test connection's poolDestroy to return, then do the pool creation.
> Return the _poolDestroy promise before connecting again

- LICENSE.md
- README.md
This allows people to more easily identify the license for the project via github (and its search) as well as trimming down the readme a little.
> Move license to its own file

- lib/tedious.js
Fix JSON parsing error for empty value.
Closes #714
> If parseJSON is true and chunksBuffer is empty, set row result to null

- .npmignore
- package.json
This replaces `.npmignore` with a whitelist of files and shaves around 85kb off the package download size.
> Reduce package size - whitelist with files prop

- lib/base.js
- test/common/templatestring.js
- test/common/unit.js
- test/tedious/tedious.js
When passing an array to a string litteral template, each item of this array is prepared.
This let you do as follow :
```
connector.query`SELECT * FROM table WHERE name in (${array})`
```
Instead of :
```
connector.query`SELECT * FROM table WHERE name in (${array[0]},${array[1]},${array[2]}...)`
connector.query`SELECT * FROM table WHERE name in (${array.map((v, i) => `@array${i}`).join(', ')})`
```
> Add support for passing array to tagged template litteral

- lib/tedious.js
When specifying the encrypt option in mssql connection options, the option is now passed to the tedious connection options.
> Passing encrypt option from mssql connection options to tedious options

- lib/connectionstring.js
- test/common/unit.js
This PR implements a shift from interpreting `Connection Timeout` in milliseconds, to interpreting it in seconds, when it comes from a connection string, as an attempt to fix #741.
Since this is a breaking change, it might be nice to expose some flag that can toggle this behavior, so the old behavior is still available for users who depend on it; so far nothing in that direction has been added.
> Interpret Connection Timeout in seconds, not milliseconds

- README.md
- lib/msnodesqlv8.js
- lib/tedious.js
Allow mutating the tedious connection by passing it to a beforeConnect handler, passed in the configuration object. 
This for example allows to tap into the tedious.debug methods and collect metrics or monitor connect, end or other events on the connection.
> semver-MAJOR add beforeConnect handler

- CHANGELOG.txt
- lib/tedious.js
- package-lock.json
- package.json
* Upgrades tedious dependency to v4 which brings support for new authentication patterns in tedious.
* Updated lib/tedious.js configuration mapping to use new `config.authentication` options paradigm.
Breaking changes:
* Support dropped in tedious library for some deprecated tedious configuration values and types
> Upgrade to tedious v4

- README.md
The example in the docs shows an immediate `unprepare` of the `PreparedStatement` which can be confusing.
We have had the docs not show the `unprepare` call resulting in #265 (it's not clear you need to unprepare) and #786 (it's unclear that you can use the prepared statement repeatedly before calling unprepare it).
I'm keeping the current example because the implications of failing to close the connection are far more devastating to an app (pool depletion) than closing the connection (having to re-prepare the query), but I have tried to clarify that the prepared statement can be used multiple times.
> Attempt to clarify use of unprepare

- package-lock.json
- package.json
Bumping the `generic-pool` dependency as we've had a couple of phantom connection issues that appear to be resolved in this release, see:
- https://github.com/coopernurse/node-pool/issues/159
- https://github.com/coopernurse/node-pool/pull/250
- https://github.com/tediousjs/node-mssql/issues/457#issuecomment-450147477
- https://github.com/typeorm/typeorm/pull/3327
fixes #457 (again)
---
https://github.com/coopernurse/node-pool/compare/v3.4.2...v3.6.0
> Bump generic-pool to 3.6.0

- lib/base.js
- lib/msnodesqlv8.js
- lib/tedious.js
This is a potential fix to #805 
~~It's still work in progress as there are some `UnhandledPromiseRejectionWarning`s, which I'm trying to get to the bottom of.~~
Thoughts on this resolution would be appreciated
---
NB: It seems that there is a problem with generic-pool where it will continually attempt to create resources no matter what and there's not a lot we can do to resolve that.
Not only that, it will continue to attempt to create resources after `drain` is called (attempting to close the pool) - I think because they are already queued up.
> NEW Add backing off to failed factoryCreate for node-pool

- CHANGELOG.txt
- README.md
- lib/base.js
- lib/msnodesqlv8.js
- lib/tedious.js
- package-lock.json
- package.json
- test/common/tests.js
Rebase of #624 
`generic-pool` does seem to be pretty broken from what I can tell (see #805)
Tarn JS seems reasonable but it doesn't appear to be actively maintained (last release was 1 year ago)
> Replace generic-pool with tarn

- CHANGELOG.txt
- lib/base.js
Branched from #808, as those changes are critical for us. We can rebase/resubmit another PR if/when #808 is merged.
- ConnectionPool starts out as healthy
- If the internal pools connections drop to 0, and a createPool call
fails, then the ConnectionPool will be flagged as unhealthy (healthy =
false)
- If an unhealthy ConnectionPool is able to successfully call
createPool, then the ConnectionPool will be reflagged as healthy
(healthy = true)
- This allows applications to decide how to deal with unhealthy
ConnectionPools (recreate, check for new config, failover, etc).
>  Added `healthy` flag to ConnectionPool

- README.md
Docs update. see #346 for context.
> Add note about params of format `@p{n}`

- lib/tedious.js
fixes #782 
According to https://github.com/tediousjs/tedious/pull/771 it's not even possible for SQL server to emit a `Null` type, so these lines won't do anything, it seems?
> Remove references to remove TYPES.Null

- CHANGELOG.txt
- lib/base.js
At the moment if you have code that calls `close` on the global connection by reference (rather than directly through `mssql.close`) then the global connection reference remains and you can't reconnect.
example:
```js
const mssql = require('mssql');
mssql.connect(config).then((connection) => {
connection.on('error', (err) => {
// this won't clean up the global connection reference
connection.close();
});
return connection;
});
```
This fix allows the global connection to be replaced if the connection is closed.
At the moment if you lose reference to the global connection there's no way to get it back. This change allows you to call `mssql.connect()` again and have the existing connection returned. It is naive and won't compare the connection configs. The global connection should not be …
> Global connection improvements

- lib/msnodesqlv8.js
- `_poolDestroy` should not return a promise (see #808)
This was overlooked as part of the tarn upgrade
> FIX _poolDestroy shouldnt return a promise

- README.md
- test/common/unit.js
Proves URL encoding works for URI connection strings
> Add test for url encoded values in connection URIs

- CHANGELOG.txt
- README.md
- appveyor.yml
- lib/table.js
- test/common/tests.js
- test/msnodesqlv8/msnodesqlv8.js
- test/tedious/tedious.js
- fixes #278 
- Coerce non date object arguments to `DateTime` and `DateTime2` columns
> NEW Bulk loading of date fields attempts to cooerce date value

- lib/base.js
What this does: It ensures the callback in in the ConnectionPool constructor and in ConnectionPool._connect() are called async.
> Fix some setImmediate() in base.ConnectionPool

- lib/connectionstring.js
- test/common/unit.js
Fixes #848 
Adds the ability to set readOnlyIntent via a connection string. Official docs: https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-2017
> Add readOnlyIntent to connection string parsing

- lib/table.js
small fix for bulk ops; converted date already exists
> remove double date creation in _makeBulk

- lib/base.js
`Request.input` has a check at [L1150](https://github.com/tediousjs/node-mssql/blob/41f374105f048a5a4fc682b88bc0a431104fae89/lib/base.js#L1150) where it's supposed to ensure that at least two parameters are passed to the function, however it only checks `if (arguments.length === 1) {` and thus calling the function without any arguments passes this test throwing a TypeError at L1170 instead of an EARGS error like expected. [example](https://runkit.com/swant/mssql-request-input-doesn-t-throw-properly)
What this does: Changes behavour to throw if 1 or fewer arguments provided
> Request.input should not allow 0 arguments

- lib/base.js
- lib/msnodesqlv8.js
- lib/tedious.js
> FIX Protect against object prototype pollution

- lib/base.js
- lib/msnodesqlv8.js
- lib/tedious.js
- package-lock.json
- package.json
- Updates tedious from 6.1.0 to 6.3.0
- Updates tarn from 1.1.4 to 1.1.5
- Updates mocha from 6.1.4 to 6.2.0
Updates poolDestroy to be promises (again) and correctly implements the close callback for nodev8 driver. This undoes a change from the early alphas when we moved from generic-pool to tarn as tarn destroy calls didn't support promises, but now it does
> Update tarn, tedious and mocha deps

- lib/table.js
- test/cleanup.sql
- test/common/tests.js
- test/common/unit.js
- test/tedious/tedious.js
Fixes #891
Adds the ability to set length for an NVARCHAR(MAX) column, which was breaking while bulk insertion.
> Fixes #891 - Bulk Insert for NVARCHAR(MAX) Fields.

- README.md
Specify that MSSQL's limitations on parameters usage applies in the usage of ES6 Tagged template literals.
See #908 for how it can cause some confusion.
> Specify limitations on parameters usage apply

- .travis.yml
- appveyor.yml
Adds Node v12 to the build matrix for testing, also adds x86/x64 tests, although not sure if the latter is really needed in 2019 😉
> Add Node v12 to build matrix

- lib/connectionstring.js
We're seeing authentication failure when updating to v6 from v5.1.0. I traced it to the fact we use "user@domain" as usernames, and the "@" is being converted to "%40".
This change decodes any items that were encoded and prevents this problem.
> Fix authentication failing when "@" is present

- lib/base/connection-pool.js
- lib/global-connection.js
- test/common/tests.js
- test/msnodesqlv8/msnodesqlv8.js
- test/tedious/tedious.js
This is an improvement on https://github.com/tediousjs/node-mssql/pull/804
Since the previous PR repeated calls to `mssql.connect()` would resolve instantly even if the pool wasn't yet in a connected state. eg:
```js
const pool = mssql.connect().then(() => console.log('first'));
const pool2 = mssql.connect().then(() => console.log('second'));
// output:
// second
// first
```
This has lead to many issues where developers are not taking into account that they shouldn't be relying on being able to call `connect()` repeatedly.
This will improve developer experience as they will need to think less about managing the state of their global connection
todo:
> FIX Repeat calls to mssql.connect() will only resolve when the pool is connected

- lib/tedious/request.js
While the `debug` package can be used to see all queries and stored procedure executions, debugging proc-heavy applications is difficult since the log doesn’t contain any parameters.
AFAIK there’s no easy way to add global parameter logging without changing this package, correct me if I'm wrong.
This PR changes the stored procedure debug line to also contain all the provided parameters. Main drawback is additional noise in debug logs, but long strings in parameters are cut short to compensate.
> Add stored procedure parameters to debug logging

- lib/base/transaction.js
- test/common/tests.js
- test/msnodesqlv8/msnodesqlv8.js
- test/tedious/tedious.js
- Adds static attribute `defaultIsolationLevel` to `Transaction` (which defaults to the current value  `ISOLATION_LEVEL.READ_COMMITTED`)
- If a user wants to change the isolation level globally for an app, they have to update `Transaction.defaultIsolationLevel` to the desired isolation level.
Example:
```javascript
Transaction.defaultIsolationLevel = ISOLATION_LEVEL.READ_UNCOMMITTED
// All transactions will now have the isolation level READ_UNCOMMITTED unless explicitly specified on each transaction
```
> Default Isolation Level for all Transactions

- lib/table.js
- test/common/tests.js
What this does:  Extends auto converting the date element to the sql.Date type
> Feature coerce sql date

- lib/msnodesqlv8/request.js
- lib/table.js
- test/cleanup.sql
- test/common/tests.js
- test/msnodesqlv8/msnodesqlv8.js
- test/prepare.sql
- test/tedious/tedious.js
Currently the `identity` and `readOnly` properties are lost when converting a recordset to a table. This change passes those properties through to the `Table` instance which is useful when trying to perform bulk operations as writing to these columns will throw errors.
> Additional column info when creating table from recordset

- CHANGELOG.txt
- README.md
- lib/base/request.js
- Piped streams shouldn't have errors passed up the pipe chain, this stops errors on the request stream being sent to the piped stream
> Don't forward errors up the pipe chain when in stream mode

- CHANGELOG.txt
- README.md
- lib/tedious/connection-pool.js
- package-lock.json
- package.json
When running tedious 8.3 the following deprecation notice is emitted:
```
tedious deprecated In the next major version of `tedious`, creating a new `Connection` instance will no longer establish a connection to the server automatically. Please use the new `connect` helper function or call the `.connect` method on the newly created `Connection` object to silence this message. internal/process/next_tick.js:61:11
```
this patch resolves this by explicitly calling `connect` on the tedious connection.
I've also remove the deprecation notice for trustServerCertificate value, using the more secure option by default.
> FIX Deprecation notice from tedious

- lib/datatypes.js
fixes #1062 
see https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect
> FIX Dont use .inspect for util.inspect anymore

- test/msnodesqlv8/msnodesqlv8.js
- Removes legacy testsuite code that conditionally runs tests based on if we are >= node 10
This is no longer required as we only support node 10+
> Drop node10 conditional test runs

- CHANGELOG.txt
- lib/global-connection.js
This fixes an issue where the reference to the global connection is not removed if the initial connection attempt fails
> FIX Remove reference to global pool on connection error

- lib/udt.js
- test/common/unit.js
fix for #322
Geography parsing would crash on geography version 2 when there is no segment.
According to [the v2 spec](https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssclrt/35a20944-9c83-4776-91c6-b5f5af5fef03), the number of segments-bytes are optional, so we have to check the input length.
I've added unit tests to demonstrate the issue.
> fix geography v2 parsing #322

- CHANGELOG.txt
- README.md
- appveyor.yml
- lib/base/request.js
- test/common/tests.js
- test/msnodesqlv8/msnodesqlv8.js
- test/tedious/tedious.js
`pipe` method should support Node.js stream back pressure and forward errors to the stream.
Modify `pipe` method to wrap the original request in a Readable stream and pipe it to the incoming stream. Errors are forwarded to the stream as well.
> Enable pipe to support back pressure and errors

- CHANGELOG.txt
- lib/msnodesqlv8/request.js
Fixes #1126 
A bit of a hacky fix here, but if the query gets terminated before all the errors are emitted, this ensures the latest error still gets emitted by our library.
> Handle queries that are terminated before all errors are handled

- README.md
Fixes the link in the readme to the new `toReadableStream` section :).
> Fix link to `toReadableStream` section in readme

- lib/base/connection-pool.js
related: https://github.com/knex/knex/pull/4235
This will just be a temp fix, but whilst knex is using this bad param we should try to deal with it for best compatibility.
The option being removed hasn't been accepted in the pool arguments since we moved to tarnjs in v6
> FIX remove bad pool param supplied by knex

- lib/base/connection-pool.js
- lib/connectionstring.js
- package-lock.json
- package.json
- test/common/unit.js
Adds support for the `TrustedServerCertificate` connection string option.
> Add support for TrustedServerCertificate to connection string parsing

- lib/shared.js
Adds the ability to have BigInts (64 bit numbers) in tagged templates.
Fixes: #1197
> Applied fix for BigInts in tagged templates

- CHANGELOG.txt
- README.md
see #1230 - "upgraded" connection string library doesn't support URI connection strings (for now)
> Update docs around uri connection strings

- lib/tedious/connection-pool.js
Ensures errors from tedious connection creation are caught and cause the promise to reject
> Catch errors thrown by new tds.Connection()

- .devcontainer/.mssql.json
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
This adds a `devcontainer` configuration that allows to easily get a development environment for `node-mssql` up and running.
See https://code.visualstudio.com/docs/remote/containers for more information.
> chore: add `devcontainer` configuration

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
This changes the devcontainer configuration to work both in local VS Code containers as well as GitHub Codespaces. GitHub Codespaces do not support the `workspaceFolder` option yet, so after starting a Codespace we'd end up in a different folder that contained the `node-mssql` source code, but did not have the `test/.mssql.json` configuration properly set up.
Instead of using a docker volume to map the `.mssql.json` file into the correct location, we just copy it over on container creation, unless it is already there.
> chore: fix the devcontainer configuration to work with local development containers and GitHub Codespaces

- README.md
> Update 7.x upgrade changes

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.txt
- lib/tedious/connection-pool.js
- lib/tedious/request.js
- package-lock.json
- package.json
- test/common/tests.js
Update tedious for a v8 release
> Update tedious version

- CHANGELOG.txt
- lib/base/prepared-statement.js
- lib/base/request.js
- lib/base/transaction.js
Yikes - I did some debugging related to #1292 and it was clear that the checks we are doing are not very sensible.
1. Give `request.stream` and `request.arrayRowMode` default values of `null`
2. Only change the value of the specific request instance's `stream` or `arrayRowMode` prop *if* it's supplied by the `parent` config.
3. Replace usage of the non-existent `this.connection` with `this.parent` for `Request` instances 🤦‍♂️ 
#1292 
> Request should use this.parent not this.connection

- CHANGELOG.txt
- lib/msnodesqlv8/connection-pool.js
Uses a different driver in the connection string when on macos/linux than on windows so that it's possible to use the library on those systems with msnodesqlv8.
This should fix the issue #1290
> Use a different driver in the msnodesqlv8 when on linux/mac

- CHANGELOG.txt
- lib/tedious/connection-pool.js
Provided driver config will no longer be overridden if it has been explicitly defined
#1331
> Do not override explicitly provided driver options

- CHANGELOG.txt
- lib/tedious/request.js
fixes #1161
todo - decide if this is a breaking change.
Possibly this means there's no need for `arrayRowMode`?!
> Allow rows that are null to be valid existing values

- CHANGELOG.txt
- README.md
- lib/table.js
- test/common/unit.js
https://github.com/tediousjs/node-mssql/issues/1087
What this does: adds new method table.rows.clear()
> Add table.rows.clear() method for chunking table row updates

- README.md
Improves clarity in the documentation around global pools, and adds some clarity/examples for using a single app-wide instance for the global pool to fix connection issues/anomalies. Even though there have been some fixes to allow repeated use of `sql.connect()`, it doesn't fix everything and there are still cases where a single instance is necessary/preferred depending on the implementation, environment, etc.
There are many github issues on this that show that this is still an issue and needs to be better represented in the documentation. I was specifically having issues inside Azure Functions and with Azure SQL, but you can see in the newer discussion in #138 that people are also having issues with AWS lambda, heroku, etc.
There was also a lot of duplicated code (there …
> Remove duplicated info, improve clarity, add samples

- CHANGELOG.txt
- lib/base/connection-pool.js
Remove pool properties that were deprecated in v5
N/A
> Remove deprecated pool properties

- CHANGELOG.txt
- package-lock.json
- package.json
1. Minor bump to debug library
2. Use the tedious Connection.reset() function when releasing connections back to the pool
N/A
> Prep for v6 end of life

- CHANGELOG.txt
- appveyor.yml
See https://github.com/TimelordUK/node-sqlserver-v8/issues/232
msnodesqlv8 accidentally broke Node 10 support in 2.4.5 release. This change conditionally installs the 2.4.4 version if testing on Node 10
https://github.com/TimelordUK/node-sqlserver-v8/issues/232
> CI Support for msnodesqlv8 on node 10

- lib/msnodesqlv8/request.js
Removes superfluous arg from `castParameter()` call.
It only accepts two args:
https://github.com/tediousjs/node-mssql/blob/b9382d425726ecdaf29972e20e1c0e115cbd8856/lib/msnodesqlv8/request.js#L17
N/A
> chore(msnodesqlv8/request): remove superfluous arg

- CHANGELOG.txt
- lib/base/connection-pool.js
- lib/base/request.js
- test/common/tests.js
- test/msnodesqlv8/msnodesqlv8.js
- test/tedious/tedious.js
This throws an error if the `useColumnNames` connection option is passed via the config object. See #1413. This option causes errors in the library, so throwing here is not a breaking change, it just gives a more helpful error.
Users should use `arrayRowMode` config instead
> Deny support for `useColumnNames` tedious option

- README.md
Small typo. According to the express docs and my own application apps.locals can be accessed through req.app.locals not req.locals.
> Fixing small typo in connecting with express documentation.

- CHANGELOG.txt
- README.md
- lib/base/connection-pool.js
This PR adds several fields related to AAD authentication. The ones added on this PR are:
1. Authentication - dictating the authentication type
2. Client ID/ClientID - used when authenticating via AAD service principal
3. Client Secret/ClientSecret - used when authenticating via AAD service principal
4. Tenant ID/TenantID  - used when authenticating via AAD service principal
5. Token - used when authenticating via AAD access token
I am completely open in renaming these fields to whichever feels more appropriate but feedback is more than welcome.
This PR is going to accomodate issue #1400
> Added support for AAD authentication via connection string

- README.md
- Fix header for upgrade notes from 8->9
- Add links to the upgrade notes for 7->8 and 8->9
N/A
> Fix README header for 8.x to 9.x upgrades

- README.md
The README showed that node < 12 support was dropped with 9.x, but based on commit 644480535933aa21d3c0677965656dc21f2949c6 it shows that node <= 12 (including node 12) support was dropped and the release notes associated with the version show the same. Updates README to align with commit message and release notes.
N/A
> Fix README to show node 12 no longer supported with 9.x

- .github/workflows/nodejs.yml
This aims to keep the release job to a single concurrency model to make sure that there aren't any race conditions when performing a release.
> chore(ci): keep release jobs in a single concurrency group

- CHANGELOG.txt
- README.md
- lib/base/connection-pool.js
- lib/error/request-error.js
- lib/msnodesqlv8/request.js
- test/common/unit.js
At the moment this port will be ignored by tedious, but this at least parses the port out as requested.
Fixes #1519
> Support named instances with ports

- CHANGELOG.txt
- lib/msnodesqlv8/connection-pool.js
This quotes generic arguments for the constructed connection string that is passed to msnodesqlv8; previous special chars in fields like password could end up breaking the connection string.
Fixes #1476
> :bug: quote sqlv8 values

- .github/workflows/nodejs.yml
Removes the release step on forks
> ci: do not run release steps on forks

- .github/dependabot.yml
Update the dependabot config to use the new [groups feature](https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/)
> ci: update dependabot to use groups

- README.md
- lib/base/connection-pool.js
- lib/tedious/connection-pool.js
- test/common/unit.js
This PR is aimed to fix a couple of issues with the previous PR: https://github.com/tediousjs/node-mssql/pull/1436 in attempt to accomodate issue #1400 
Changes include:
1. Authentication now uses the standard values defined on [.NET Platform Extension 7](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=dotnet-plat-ext-7.0)
2. Fixes the breakage of standard/basic connection which has been reported in #1460
> Fixed issues related to previous PR regarding AAD authentication via connection string

- package-lock.json
- package.json
Bumps the minimum support node version from 10 to 14
Support was dropped elsewhere as part of #1547 
> chore(package): bump min node version from 10 to 14

- bin/mssql
- lib/base/connection-pool.js
- lib/base/prepared-statement.js
- lib/base/request.js
- lib/base/transaction.js
- lib/msnodesqlv8/connection-pool.js
- test/common/cli.js
- test/common/templatestring.js
- test/common/tests.js
- test/common/times.js
- test/common/unit.js
- test/msnodesqlv8/msnodesqlv8.js
- test/tedious/tedious.js
Allows redundant `require.cache` calls to be bypassed for builtin modules, saving a few yoctoseconds.
See https://nodejs.org/api/modules.html#core-modules and [discussion in nodejs/node repo regarding why `require.cache` calls are redundant for builtins](https://github.com/nodejs/node/pull/37246/files#r588397158).
N/A
> perf: use `node:` prefix to bypass require.cache call for builtins

- lib/base/prepared-statement.js
- lib/base/request.js
Removes unused capture groups `(` `)` inside regex.
A capture group is intended to store its matched text so it can be used later on e.g. in text replacements, so the regex engine has to do extra work every time a capture group is matched compared to a non-capture group.
The captured text is never used elsewhere here.
N/A
> perf: remove unused regex capture groups

- .github/dependabot.yml
Dependabot can now update github actions as new versions are released.
> ci: add dependabot config for github actions

- .github/workflows/nodejs.yml
- lib/datatypes.js
- package-lock.json
- package.json
Reverts tediousjs/node-mssql#1664
This has been released as a patch release when it should have been a major release (grr).
> Revert "chore(deps): bump @azure/identity and tedious"

- .releaserc
This should allow us to use the `feat!` commit prefix for breaking changes.
> ci: use conventionalcommits release preset

- README.md
- Clarify documentation on how to use the msnodesqlv8 driver
- Explicitly document which driver is required for Windows/Trusted Connection Authentication & provide example code 
- Refer to `msnodesqlv8` exclusively by its package name
N/A
> Improve msnodesqlv8 documentation in README

- lib/shared.js
PR fixes a TypeError "Cannot mix BigInt and other types, use explicit conversions" when passing a bigint parameter to request
The following example crashed with error:
```javascript
const request = new mssql.Request();
request.input('bigintpara', BigInt('4294967294'));
```
Now it does not raise an error.
> fix: TypeError with BigInt param

- test/common/tests.js
- test/msnodesqlv8/msnodesqlv8.js
- test/tedious/tedious.js
bigint params may throw when compared to ints
#1677 
> test: make sure bigint intputs do not throw

- README.md
Minor documentation update to clarify when events must be attached to the request when streaming.
https://github.com/tediousjs/node-mssql/issues/1698
> Clarify timing requirements of streaming events in README

- .github/workflows/nodejs.yml
The sql-2017 container is crashing on ubuntu 2017; this seems to be a host OS issue because the exact same docker tag used to pass but is now failing. It last passed at the beginning of this month, so some upgrade/change in feb this year has caused the problem.
~The aim to to get the 2017 image running on the 20.04 runner and the rest on 22.04~
The ubuntu 20.04 runner [is being removed](https://github.com/actions/runner-images/issues/11101) from support, so this isn't a long term fix. ~We should try to run on 24.04 instead~. 24.04 has the same issue, but I'll upgrade the runners for the ones that work and downgrade the 2017 runner for now.
---
It seems that the 2017 container won't run on 22.04 nor 24.04, so 20.04 is the only one that can be used for now.
I think the …
> ci: upgrade linux runner to 24.04

- index.js
- lib/datatypes.js
- lib/utils.js
- msnodesqlv8.js
- tedious.js
This PR adds missing `'use strict'` directives to the cjs files in this repo. Strict mode can improve performance by eliminating some JavaScript features that hinder optimizations. It also helps avoid subtle bugs by enforcing more consistent scoping and variable declarations.
The [MDN article on strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) alludes to it, but the V8 JS engine used by Node will use more optimised execution paths when strict mode is enabled. See [related Stack Overflow discussion](https://stackoverflow.com/questions/38411552/why-use-strict-improves-performance-10x-in-this-example) for an example.
N/A
> chore: add missing `'use strict'` directives

- lib/shared.js
Destructures the datatypes import as it was the last import in the codebase using the old style.
N/A
> style(lib/shared): destructure datatypes import

- .github/workflows/nodejs.yml
Adds next LTS, Node 24, to test matrix in CI job.
N/A
> ci(nodejs): add node 24 to test matrix
