tediousjs/node-mssql

src/tedious.coffee

This PR adds the missing `isCaseSensitive`, `isIdentity`, `isWriteable` to the row metadata.

Added metadata isCaseSensitive, isIdentity, isWriteable

---

README.md

In the Error Codes section, clarified that errors have err.name, err.code and err.message properties.
Fixed various trivial typos.

Clarified error fields, fixed various trivial typos.

---

package.json

Upgrades node-mssql to use version 1.13.x of tedious . There don't seem to be any breaking changes but a major improvement in performance.
Signed-off-by: Luca Moser <Luca Moser>

Upgrades tedious version

---

src/tds.coffee

~400x speed improvement to parseGuid: https://gist.run/?id=b1843965d498b4020858dbeb1483a6f7

parseGuid performance tuning

---

README.md

Fix semicolon usage for Promise based example

---

src/tedious.coffee

Hi,
Guess is a typo or should we have FloatN definition ?
Thanks for a great job.

Fix possible typo

---

lib/base.js
test/common/unit.js

Also included test against getTypeByValue to simplify future type inference confirmations
Fixes #475

Fix type inference of non-integer numbers (#475)

---

lib/base.js

set acquireTimeout on generic pool

---

README.md

This fixes various links in the README by either a) fixing the links or b) correcting formatting so as to create the intended link.

Fix links/markdown of headings in README

---

lib/msnodesqlv8.js

Allows TVPs to be used with msnnodesqlv8 driver

---

README.md

DOCS Request timeout config via connection string

---

README.md

Improve docs around pool creation + ensuring it's always ready

---

.github/ISSUE_TEMPLATE.md

What this does: strongly encourages easily readable and replicable issue reports. I hope.

Strongly recommend using the issue template to report issues

---

.travis.yml
CHANGELOG.txt
appveyor.yml
package-lock.json
package.json

fixes https://github.com/tediousjs/node-mssql/issues/733
Breaking change since it is not compatible with Node < 6

chore: upgrade tedious

---

CHANGELOG.txt

Add changelog for v4.2.3, v4.3.0

---

README.md

Remove docs around next tag

---

README.md
lib/base.js
lib/msnodesqlv8.js
lib/tedious.js
package.json

NEW Add options parameter to bulk to enable passthrough to tedious

---

.travis.yml

This will automatically publish the docs to gh-pages on tag :)

Automatically publish docs on tag

---

README.md

Fix docs for pause/resume example

---

CHANGELOG.txt

Update changelog for v5

---

package-lock.json
package.json

Bump outdated dependencies

---

README.md

Fix missing `connect` call from docs

---

lib/base.js
lib/tedious.js
package-lock.json
package.json

- Upgrade `generic-pool`
- Make sure that destroying a closed tedious connection resolves

Upgrade generic-pool

---

CHANGELOG.txt
README.md
lib/base.js
lib/datatypes.js
lib/tedious.js
lib/udt.js
package-lock.json
package.json
test/common/cli.js
test/common/tests.js
test/common/times.js
test/common/unit.js
test/msnodesqlv8/msnodesqlv8.js
test/tedious/tedious.js

Upgrades to Tedious v6
Upgrades other deps
Linting fixes

Upgrade to Tedious v6

---

lib/base.js

Dont modify the passed in config object

---

lib/base.js
test/cleanup.sql
test/common/tests.js
test/msnodesqlv8/msnodesqlv8.js
test/prepare.sql
test/tedious/tedious.js

- see #832 
Added test coverage to prove stability of pause/resume of streamed requests (tedious only)

Update streaming tests

---

lib/msnodesqlv8.js

FIX Attempt to prevent double callbacks on msnodesqlv8 driver

---

lib/tedious.js

FIX connection that throws errors now do not deplete the pool

---

README.md

Fix bad doc examples

---

lib/base.js
lib/connectionstring.js
lib/datatypes.js
lib/msnodesqlv8.js
lib/table.js
lib/tedious.js
lib/udt.js
lib/utils.js
package-lock.json
package.json
test/common/cli.js
test/common/templatestring.js
test/common/tests.js
test/common/times.js
test/common/unit.js
test/msnodesqlv8/msnodesqlv8.js
test/tedious/tedious.js

- Upgraded dependencies (including linting rules)
- Fixed linting errors
- Added a util function for correctly testing `hasOwnProperty` of objects

Upgrade dependencies and fix linting rules

---

CHANGELOG.txt
README.md

We haven't been keeping the changelog nor the upgrade guide up to date, so here are the latest bits and bobs

Updated changelog and upgrade guide

---

README.md
lib/base/request.js

Add docs about pool management and how the global connection pool works.
see #961

Add docs about pool management

---

README.md

Fix a docs error where we missed an await on a query.

Add missing await to docs

---

README.md

Using spaces instead of tabs in our docs (for consistency)

Fix docs indentation

---

lib/tedious/connection-pool.js
test/scripts/appveyor.ps1

Fix a bug where connections are not encrypted by default (as per docs)

Make sure connections are encrypted by default

---

lib/base/request.js
test/common/unit.js

Fix issue with tagged template literal query with empty array

---

lib/tedious/index.js
package-lock.json
package.json

What this does: Points to latest tedious version, which have some fixes for Large TVP performance and memory consumption. Solves #1006 
Refer: https://github.com/tediousjs/tedious/issues/879#issuecomment-596144548,  https://github.com/tediousjs/tedious/issues/971#issuecomment-596144540

Bumped tedious version to latest

---

lib/msnodesqlv8/request.js
test/common/tests.js
test/msnodesqlv8/msnodesqlv8.js
test/tedious/tedious.js

Attempt to handle multiple error events

---

appveyor.yml

Update appveyor builds to test with latest applicable versions of msnodesqlv8

Test against latest msnodesqlv8 versions

---

.travis.yml
appveyor.yml

Add node 14 to test suite

---

README.md

Closes #938
Just helps newcomers to start coding with the library faster.

Add Basic Response Schema

---

.travis.yml
CHANGELOG.txt
appveyor.yml
package-lock.json
package.json

Bumps min supported version of node to 10+
closes #1038

Bump node support to v10+

---

package-lock.json

Security patches

---

CHANGELOG.txt
README.md
lib/msnodesqlv8/request.js
test/common/tests.js
test/msnodesqlv8/msnodesqlv8.js
test/tedious/tedious.js

Fix streaming trailing rows with msnodesqlv8 driver

---

README.md

Clarify support of msnodesqlv8 is v1 only

---

CHANGELOG.txt
README.md
appveyor.yml
lib/msnodesqlv8/request.js
test/msnodesqlv8/msnodesqlv8.js

msnodesqlv8 v2 support

---

lib/base/connection-pool.js

Reverts tediousjs/node-mssql#1172
see https://github.com/knex/knex/pull/4236 - now released in knex 0.21.16

Revert "FIX remove bad pool param supplied by knex"

---

package-lock.json
package.json

Bump outdated deps

---

package-lock.json
package.json

Merge 6 and upgrade deps

---

lib/msnodesqlv8/connection-pool.js
lib/shared.js
package-lock.json
package.json
test/common/cli.js
test/common/templatestring.js
test/common/tests.js
test/msnodesqlv8/msnodesqlv8.js
test/tedious/tedious.js

Upgrade tedious dependency; linting fixes

---

README.md

Updates documentation for Tedious Authentication regarding to the discussion in PR https://github.com/tediousjs/node-mssql/pull/1208.

Update Tedious authentication documentation

---

CHANGELOG.txt
lib/base/connection-pool.js
lib/msnodesqlv8/connection-pool.js
lib/tedious/connection-pool.js

Attempt to validate connections before releasing them
todo:

NEW Validate tedious requests are healthy by making a request

---

CHANGELOG.txt
lib/base/connection-pool.js
package-lock.json
package.json
test/common/unit.js

Fix cloning of config objects

---

CHANGELOG.txt
lib/msnodesqlv8/connection-pool.js

NEW Add useUTC support to msnodesqlv8 driver

---

lib/tedious/request.js
package-lock.json
package.json
test/common/tests.js

- Updates changelog
- Bump tedious version
We are seeing some failures because of a bug in tedious which I've opened a PR for (https://github.com/tediousjs/tedious/pull/1244)

Prep for 7.0.0 release

---

README.md

I updated the readme for Node V8 driver with more informations about connection string and the macOS usage (ran on my mac)
feel free to ask more information or request change on this pr :)

upgrade README.md for Node V8 driver

---

CHANGELOG.txt
lib/base/connection-pool.js

NEW add parseJSON config support to query string parsing

---

README.md

Update the pool management docs so the examples are a bit more "real world" (consistent return types, don't store bad pools, etc).

DOCS Update pool management example

---

lib/base/connection-pool.js

Use passed value for encrypt in connection string

---

CHANGELOG.txt

Fix changelog typo

---

CHANGELOG.txt
lib/base/connection-pool.js

Fix request timeout connection string key

---

lib/tedious/request.js

Fix handling of errors when adding rows to bulk operations

---

lib/msnodesqlv8/request.js
test/cleanup.sql
test/common/tests.js
test/msnodesqlv8/msnodesqlv8.js
test/prepare.sql
test/tedious/tedious.js

issue #1274 
Takes any output parameters that have values pass in and assigns those values before executing the proc

Fix msnodesqlv8 output param initial values

---

lib/msnodesqlv8/request.js
lib/tedious/request.js

Catch errors from table._makeBulk()

---

package-lock.json
package.json

Update mocha dependency

---

README.md

Fixes a typo in the readme file

fix typo connecton -> connection

---

.travis.yml
appveyor.yml

Adds node 14 to our testing matrix
N/A

Add node 14 to test matrix

---

CHANGELOG.txt
package-lock.json
package.json

Updates the tarn and debug deps
closes #1322 

Update tarn & debug dependencies

---

CHANGELOG.txt
README.md
lib/base/index.js
lib/msnodesqlv8/index.js
lib/msnodesqlv8/request.js
lib/shared.js
lib/tedious/index.js
lib/tedious/request.js
test/common/tests.js
test/common/unit.js
test/msnodesqlv8/msnodesqlv8.js
test/tedious/tedious.js

closes #1170
supersedes #1171 
---
Thanks to @anton-johansson for his first pass at this

Allow processing of return column values by callback

---

README.md

Update the upgrade guide in the readme
N/A

Update readme changes for v7 - v8 upgrade

---

CHANGELOG.txt
appveyor.yml

CI Support for msnodesqlv8 on node 10 (v7)

---

CHANGELOG.txt
lib/table.js
test/common/unit.js

Incapsulate primary key constraint with square brackets

fix missing square bracket on constraint

---

.travis.yml
CHANGELOG.txt
appveyor.yml
lib/tedious/request.js
lib/utils.js
package-lock.json
package.json
test/common/unit.js

Updates the tedious (and other) dependencies including fixing new linting issues due to upgrade

Update dependencies and lint fixes

---

.github/workflows/gh-pages.yml
package.json

Fix the gh-pages release task
n/a

chore(ci): fix page branch update

---

.github/workflows/gh-pages.yml

Update the github pages push workflow
n/a

ci: fix gh-pages action

---

CHANGELOG.txt
lib/msnodesqlv8/connection-pool.js

Fix for #1542.

---

.github/workflows/nodejs.yml
package-lock.json
package.json

Reverts tediousjs/node-mssql#1518

Revert "chore(deps): bump tedious from 15.0.1 to 16.4.0"

---

.github/workflows/nodejs.yml
CHANGELOG.txt
package-lock.json
package.json

feat!: upgrade tedious, drop node <= 14 support

---

README.md

I propose to update the example so it's 100% obvous how to use the code. If someone copy paste the code it will not work. I know it seems trivial but it make a difference.

Improve examples in README

---

.github/workflows/nodejs.yml
lib/datatypes.js
package-lock.json
package.json

feat!: upgrade tedious

---

.github/workflows/nodejs.yml
package-lock.json
package.json

ci: move release process to node 18

---

.github/workflows/gh-pages.yml

ci: move to action based pages deploy

---

lib/base/request.js

This addresses a few typos and inconsistencies with comments that I noticed while digging into the code 🙂 
None

refactor: address some doc comment typos

---

.github/workflows/nodejs.yml

ci: remove windows-2019 from CI runs as it is EOL
